### ISSUE TITLE
very helpful project 

### ISSUE THREAD

**Issue by GianniGi** [kkatano/bakeneko-80-case#1]
Hello, your project is very intersting, I've seen on GH.
I think that it doesn't have so much followers because sourcing the parts is very difficult... nobody wants to do that.
I hope that someone jumps in and sells us your design. 
https://geekhack.org/index.php?topic=106561.0

Thanks for what you did.

**Comment by kkatano** [comment]
@GianniGi Thank you for your feedback. If there are a lot of requests, I might do GB. Anyway, right now I'll focus on the work to release the first version.
